name: Release

on:
  push:
    tags:
      - '*'

jobs:
  docker:
    name: Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Use Docker builder
        uses: docker/setup-buildx-action@v1.3.0

      - name: Login to Container Registry
        uses: docker/login-action@v1.9.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker build and push
        uses: docker/build-push-action@v2.5.0
        with:
          context: ./
          file: ./Dockerfile
          labels: |
            org.opencontainers.image.authors=${{ github.repository_owner }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
          tags: |
            ghcr.io/${{ secrets.DOCKER_IMAGE }}:latest
#            ghcr.io/${{ secrets.DOCKER_IMAGE }}:${{ github.ref }}
          push: true

  npm:
    name: npm package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: 15
          registry-url: https://registry.npmjs.org/
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

#  binaries:
#    name: Binaries
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2.3.4
#      - uses: actions/setup-node@v2.1.5
#        with:
#          version: 14
#      - run: npm install
#      - run: npx pkg .
